// Import global CSS (Tailwind + app styles)
import '../styles/globals.css'
import Navigation from '../components/Navigation'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="font-sans bg-white text-black">
        <Navigation />
        {children}
      </body>
    </html>
  )
}
